# Generated by Django 4.2.5 on 2023-09-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
    ]
